"""
SQLAlchemy model for the Obra (work) table.
"""

import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Enum, String, Text
from sqlalchemy.orm import relationship

from app.database import Base


class ModoObra(str, enum.Enum):
    """Creation modes of a work."""
    MANUAL = "MANUAL"
    TESTIGO = "TESTIGO"


class Obra(Base):
    """
    Represents a work generated and degraded in RUIDO.

    Attributes:
        id: Unique UUID identifier.
        prompt_original: Prompt the user provided to generate the text.
        texto_base: Text generated by the AI before degradation.
        texto_final: Text after applying degradation.
        modo: Creation mode (MANUAL or TESTIGO).
        creado_en: Creation timestamp.
    """
    __tablename__ = "obras"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    prompt_original = Column(Text, nullable=False)
    texto_base = Column(Text, nullable=False)
    texto_final = Column(Text, nullable=True)
    modo = Column(Enum(ModoObra), nullable=False, default=ModoObra.MANUAL)
    creado_en = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))

    # Relationship with certificates
    certificados = relationship("Certificado", back_populates="obra")
